apiVersion: v1
kind: ConfigMap
metadata:
  name: mdm-config
data:  
    spring.datasource.url: jdbc:mysql://mysql.default.svc.cluster.local:3306/shikshadb?user=testpass&password=testpass&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    restapi.mdm.url: http://mdm:8090/
    AWS_REGION: us-east-1
    kubernetes.profile: "Y"
    jwt.aws.userPoolId: us-east-1_d7gTXDzXK
    cognito.app.clientid: 4d0rspobol474rft7nq57krjjq
    

---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: mdm
  name: mdm
spec:
  replicas: 1
 
  selector:
    matchLabels:
      app: mdm  
  template:
    metadata:      
      labels:
        app: mdm
    spec:
      serviceAccountName: cognito-access
      containers:
      - image: pavithravasudevan/administration-service:0.0.1
        name: mdm
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "400m"
          limits:
            memory: "800Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: mdm-config
       
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: mdm
  name: mdm
spec:
  ports:
  - name: 8090-8090
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: mdm
  type: ClusterIP
status:
  loadBalancer: {}